### ISSUE TITLE
At least one output file must be specified

### ISSUE THREAD

**Issue by CodeF53** [vladmandic/sd-extension-steps-animation#4] opened 2023-01-23 03:29 UTC
```
Steps animation params: {███████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  2.92it/s]
  "prompt": "masterpiece, best quality,\n1girl, cute, very long hair, pink hair, animal ears, pink cat ears, blue eyes, medium breasts, white animal ear fluff,  blush, \n((comic)), ((black border)), ((black theme)), speech bubble, english text, ((meme)),",
  "negative": "(bad_prompt:0.8), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, disfigured, deformed, malformed, mutant, monstrous, ugly, gross, disgusting, old, fat, obese, out of frame, poorly drawn, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, out of focus, longneck, long body, furry, fuzzy, abstract, transparency, flabby, name tag, siamese twins, anal, mosaic censor, pixels censor, censor bars, loli, futa, futanari, child,\n((white border)), ((white background)), ((out of frame))\nreal life, realistic,",
  "seed": 551348728,
  "sampler": "Euler a",
  "cfgscale": 7,
  "steps": 25,
  "current": 25,
  "skip": 0,
  "info": "masterpiece best quality, 1girl cute very long hair pink hair animal ears pink cat ears blue eyes medium breasts white animal ear fluff  blush, comic black border black theme speech bubble english text meme, Negative prompt badprompt08 lowres bad anatomy bad hands text error missing fingers extra digit fewer digits cropped worst quality low quality normal quality jpeg artifacts signature watermark username blurry artist name disfigured deformed malformed mutant monstrous ugly gross disgusting old fat obese out of frame poorly drawn poorly drawn hands missing limb floating limbs disconnected limbs malformed hands out of focus longneck long body furry fuzzy abstract transparency flabby name tag siamese twins anal mosaic censor pixels censor censor bars loli futa futanari child, white border white background out of frame, real life realistic, Steps 25 Sampler Euler a CFG scale 7 Seed 551348728 Size 512x512 Model hash 89d59c3dde Clip skip 2 ENSD 31337",
  "model": "unknown",
  "embedding": "none",
  "faces": null,
  "timestamp": "20230122202728",
  "inpath": "outputs/txt2img-images\\intermediate",
  "outpath": "outputs/txt2img-images\\animation",
  "codec": "libx264",
  "duration": 5,
  "interpolation": "mci",
  "loglevel": "info",
  "cli": "ffmpeg -hide_banner -loglevel {loglevel} -hwaccel auto -y -framerate {framerate} -i \"{inpath}/%5d.jpg\" -r {videorate} {preset} {minterpolate} {flags} -metadata title=\"{description}\" -metadata description=\"{info}\" -metadata author=\"stable-diffusion\" -metadata album_artist=\"{author}\" \"{outfile}\"",
  "framerate": 5.0,
  "videorate": 30,
  "author": "https://github.com/vladmandic",
  "preset": "-vcodec libx264 -preset medium -crf 23",
  "flags": "-movflags +faststart",
  "ffmpeg": "C:\\ffmpeg\\bin\\ffmpeg.EXE",
  "minterpolate": "-vf minterpolate=mi_mode=mci,fifo",
  "outfile": "outputs/txt2img-images\\animation\\551348728-masterpiece best quality, 1girl cute very long hair pink hair animal ears pink cat ears blue eye.mp4",
  "description": "masterpiece, best quality,\n1girl, cute, very long hair, pink hair, animal ears, pink cat ears, blue eyes, medium breasts, white animal ear fluff,  blush, \n((comic)), ((black border)), ((black theme)), speech bubble, english text, ((meme)), | negative (bad_prompt:0.8), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, disfigured, deformed, malformed, mutant, monstrous, ugly, gross, disgusting, old, fat, obese, out of frame, poorly drawn, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, out of focus, longneck, long body, furry, fuzzy, abstract, transparency, flabby, name tag, siamese twins, anal, mosaic censor, pixels censor, censor bars, loli, futa, futanari, child,\n((white border)), ((white background)), ((out of frame))\nreal life, realistic, | seed 551348728 | sampler Euler a | cfgscale 7 | steps 25 | current 25 | model unknown | embedding none | faces None | timestamp 20230122202728 | interpolation mci"
}
Steps animation creating movie sequence: outputs/txt2img-images\animation\551348728-masterpiece best quality, 1girl cute very long hair pink hair animal ears pink cat ears blue eye.mp4
Steps animation CMD: ffmpeg -hide_banner -loglevel info -hwaccel auto -y -framerate 5.0 -i "outputs/txt2img-images\intermediate/%5d.jpg" -r 30 -vcodec libx264 -preset medium -crf 23 -vf minterpolate=mi_mode=mci,fifo -movflags +faststart -metadata title="masterpiece, best quality,
1girl, cute, very long hair, pink hair, animal ears, pink cat ears, blue eyes, medium breasts, white animal ear fluff,  blush,
((comic)), ((black border)), ((black theme)), speech bubble, english text, ((meme)), | negative (bad_prompt:0.8), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, disfigured, deformed, malformed, mutant, monstrous, ugly, gross, disgusting, old, fat, obese, out of frame, poorly drawn, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, out of focus, longneck, long body, furry, fuzzy, abstract, transparency, flabby, name tag, siamese twins, anal, mosaic censor, pixels censor, censor bars, loli, futa, futanari, child,
((white border)), ((white background)), ((out of frame))
real life, realistic, | seed 551348728 | sampler Euler a | cfgscale 7 | steps 25 | current 25 | model unknown | embedding none | faces None | timestamp 20230122202728 | interpolation mci" -metadata description="masterpiece best quality, 1girl cute very long hair pink hair animal ears pink cat ears blue eyes medium breasts white animal ear fluff  blush, comic black border black theme speech bubble english text meme, Negative prompt badprompt08 lowres bad anatomy bad hands text error missing fingers extra digit fewer digits cropped worst quality low quality normal quality jpeg artifacts signature watermark username blurry artist name disfigured deformed malformed mutant monstrous ugly gross disgusting old fat obese out of frame poorly drawn poorly drawn hands missing limb floating limbs disconnected limbs malformed hands out of focus longneck long body furry fuzzy abstract transparency flabby name tag siamese twins anal mosaic censor pixels censor censor bars loli futa futanari child, white border white background out of frame, real life realistic, Steps 25 Sampler Euler a CFG scale 7 Seed 551348728 Size 512x512 Model hash 89d59c3dde Clip skip 2 ENSD 31337" -metadata author="stable-diffusion" -metadata album_artist="https://github.com/vladmandic" "outputs/txt2img-images\animation\551348728-masterpiece best quality, 1girl cute very long hair pink hair animal ears pink cat ears blue eye.mp4"
Trailing option(s) found in the command: may be ignored.
Input #0, image2, from 'outputs/txt2img-images\intermediate/%5d.jpg':
  Duration: 00:00:05.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 512x512 [SAR 1:1 DAR 1:1], 5 fps, 5 tbr, 5 tbn
At least one output file must be specified
Steps animation removing 25 files from temp folder: outputs/txt2img-images\intermediate
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:09<00:00,  2.76it/s]
```

**Comment by CodeF53** [comment] 2023-01-23 03:46
This appears to happen when I use newlines in the prompt

**Comment by vladmandic** [comment] 2023-01-23 12:06
updated, can you test?

**Comment by CodeF53** [comment] 2023-01-23 16:00
Will later tonight

**Comment by vladmandic** [comment] 2023-01-25 04:16
closing as resolved as i cannot reproduce anymore.

**Closed by vladmandic** 2023-01-25 04:16 UTC
Labels: bug
